# Generated by Django 4.2.30 on 2026-07-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0002_employeeprofile_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='daily_salary',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
    ]
