# Generated by Django 4.2.30 on 2026-07-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0003_employeeprofile_daily_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='daily_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
