# Generated by Django 4.2.30 on 2026-07-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0004_alter_employeeprofile_daily_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='employee_profiles/'),
        ),
    ]
