# Generated by Django 4.2.30 on 2026-07-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0005_employeeprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='biometric_lock_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='failed_biometric_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='is_biometric_locked',
            field=models.BooleanField(default=False),
        ),
    ]
