# Generated by Django 4.2.30 on 2026-07-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0006_employeeprofile_biometric_lock_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='ot_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
