# Generated by Django 4.2.30 on 2026-07-29 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_shift_attendancerecord_shift_end_time_and_more'),
        ('employee_management', '0007_employeeprofile_ot_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='attendance.shift'),
        ),
    ]
