# Generated by Django 4.2.30 on 2026-07-29 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_management', '0008_employeeprofile_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='custom_check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='custom_check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeTimingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=150)),
                ('previous_check_in_time', models.TimeField(blank=True, null=True)),
                ('previous_check_out_time', models.TimeField(blank=True, null=True)),
                ('updated_check_in_time', models.TimeField(blank=True, null=True)),
                ('updated_check_out_time', models.TimeField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('employee_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timing_audit_logs', to='employee_management.employeeprofile')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timing_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
