# Generated by Django 4.2.30 on 2026-07-29 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0014_overtimerecord_assigned_shift_and_more'),
        ('employee_management', '0009_employeeprofile_custom_check_in_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeShiftAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=150)),
                ('previous_shift_name', models.CharField(max_length=100)),
                ('new_shift_name', models.CharField(max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('employee_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_audit_logs', to='employee_management.employeeprofile')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_updates', to=settings.AUTH_USER_MODEL)),
                ('new_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_shift_audits', to='attendance.shift')),
                ('previous_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_shift_audits', to='attendance.shift')),
            ],
        ),
    ]
