# Generated by Django 4.2.30 on 2026-07-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0003_organizationprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminatedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('role', models.CharField(max_length=20)),
                ('terminated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
