# Generated by Django 4.2.30 on 2026-07-24 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='early_checkout_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_early_checkout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='lateness_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AdminAttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.TimeField(default='09:00:00')),
                ('check_out_time', models.TimeField(default='18:00:00')),
                ('working_days', models.JSONField(default=list)),
                ('custom_holidays', models.JSONField(default=list)),
                ('admin', models.OneToOneField(limit_choices_to={'role': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
