# Generated by Django 4.2.30 on 2026-07-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord_early_checkout_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminattendancesettings',
            name='default_daily_salary',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
    ]
