# Generated by Django 4.2.30 on 2026-07-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancelog_device_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='failed_attempts_count',
            field=models.IntegerField(default=0),
        ),
    ]
