# Generated by Django 4.2.30 on 2026-07-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancelog_failed_attempts_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='employee_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
