# Generated by Django 4.2.30 on 2026-07-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendancelog_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='similarity_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='similarity_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
