# Generated by Django 4.2.30 on 2026-07-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendancelog_similarity_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminattendancesettings',
            name='enable_overtime',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminattendancesettings',
            name='overtime_rate_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=4),
        ),
    ]
