# Generated by Django 4.2.30 on 2026-07-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_adminattendancesettings_enable_overtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='overtime_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
