# Generated by Django 4.2.30 on 2026-07-25 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0009_attendancerecord_overtime_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminattendancesettings',
            name='enable_overtime',
        ),
        migrations.RemoveField(
            model_name='adminattendancesettings',
            name='overtime_rate_multiplier',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='overtime_amount',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='overtime_hours',
        ),
        migrations.CreateModel(
            name='OvertimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('calculated_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('check_in_image', models.ImageField(blank=True, null=True, upload_to='attendance_captures/ot_checkin/')),
                ('check_out_image', models.ImageField(blank=True, null=True, upload_to='attendance_captures/ot_checkout/')),
                ('similarity_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-check_in'],
            },
        ),
    ]
