# Generated by Django 4.2.30 on 2026-07-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_remove_adminattendancesettings_enable_overtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminattendancesettings',
            name='default_ot_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10),
        ),
    ]
