# Generated by Django 4.2.30 on 2026-07-29 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_alter_attendancerecord_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerecord',
            name='assigned_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_records', to='attendance.shift'),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='employee_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='ot_status',
            field=models.CharField(default='APPROVED', max_length=20),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='shift_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
